---
kind: pipeline
name: compliance

steps:
- name: "Compliance"
  image: python:3.8
  commands:
  - scripts/install
  - scripts/test

trigger:
  branch:
    - master
  event:
    exclude:
    - push
